"""SSH transport using the system OpenSSH client.

- Honours ~/.ssh/config (aliases, keys, agent, ProxyJump, NVIDIA Sync entries).
- Host keys are always verified (StrictHostKeyChecking=yes). The user's own
  known_hosts settings are left alone; keys trusted through Newton live in a
  separate file added as a global known_hosts file. New keys are only ever
  *captured* (KnownHostsCommand records what the host presents, which works through
  ProxyCommand/Tailscale aliases too) and trusted after the user approves them.
- Scripted connections neutralise ~/.ssh/config options that would make them
  interactive, multiplexed or forwarding more than asked (RemoteCommand, RequestTTY,
  ControlMaster, ForwardAgent, LocalForward...).
- Remote commands are fixed strings defined in this module; the only variable
  parts are validated integers, agentd-generated hex stage names and shlex-quoted
  settings. Nothing model-generated ever reaches a remote shell.
- Job traffic goes over an `ssh -N -L` tunnel to the worker's HTTP API, which
  listens on a Unix socket in ~/.newton (0700): only its owner can reach it.
"""

from __future__ import annotations

import asyncio
import base64
import binascii
import hashlib
import io
import json
import os
import re
import secrets
import shlex
import shutil
import tarfile
import tempfile
import time
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .base import RunnerError
from .worker_client import WorkerClient, WorkerClientRunner


def _sh(script: str) -> str:
    """Run a fixed script under POSIX sh, whatever the user's login shell is
    (fish/csh would not parse if/then or `set -e`)."""
    return "sh -c " + shlex.quote(script)


# Each upload extracts into its own staging dir ($1, generated by agentd); the
# bootstrap swaps it in under its lock, and only after every check passed.
REMOTE_UPLOAD_SOURCE = _sh(
    'set -e; umask 077; d="$HOME/.newton"; mkdir -p "$d"; chmod 700 "$d"; '
    'rm -rf "$d/$1"; mkdir "$d/$1"; tar -xzf - -C "$d/$1"'
)
# A command string, not a secret: the token itself arrives on stdin.
# Each Newton install writes its own file ($1 = a hash of its token, never the token).
REMOTE_WRITE_TOKEN = _sh(  # noqa: S105
    'umask 077 && mkdir -p "$HOME/.newton/tokens" && cat > "$HOME/.newton/tokens/$1"'
)
REMOTE_PROBE = "uname -srm"
# Markers: rc files that print on non-interactive logins must not corrupt the value.
REMOTE_HOME = _sh('printf "NEWTON-HOME:%s:END\\n" "$HOME"')
# Is the worker alive on the host itself? (Tells "worker down" from "forward refused".)
REMOTE_WORKER_ALIVE = _sh(
    'd="$HOME/.newton"; test -S "$d/worker.sock" || exit 1; '
    'pid=$(sed -n "s/.*\\"pid\\": *\\([0-9][0-9]*\\).*/\\1/p" "$d/worker.json"); '
    'test -n "$pid" && kill -0 "$pid"'
)
WORKER_SOCKET = ".newton/worker.sock"  # relative to the remote $HOME
STAGE_RE = re.compile(r"^src\.stage-[0-9a-f]{16}$")
DIGEST_RE = re.compile(r"^[0-9a-f]{64}$")
# Must match newton_worker.PROTOCOL_VERSION; the worker is not imported here.
WORKER_PROTOCOL = 4


def new_stage() -> str:
    return f"src.stage-{secrets.token_hex(8)}"


def remote_bootstrap_command(stage: str, args: list[str]) -> str:
    if not STAGE_RE.match(stage):
        raise ValueError(f"invalid stage name {stage!r}")
    script = f'"$HOME/.newton/{stage}/bootstrap.sh"'
    return " ".join(["sh", script, "--stage", stage, *(shlex.quote(a) for a in args)])


# bootstrap.sh exit code → (error code, transient, what the user should know).
# Codes 1, 2, 126 and 127 come from the shell itself and map to "bootstrap_crashed".
BOOTSTRAP_ERRORS: dict[int, tuple[str, bool, str]] = {
    64: ("config", False, "bootstrap.sh rejected its arguments or install location"),
    65: ("token_missing", False, "the worker token was not written to the host"),
    66: (
        "python_missing",
        False,
        "Python >= 3.9 was not found on the host. Install python3 or set the host's python path.",
    ),
    67: (
        "worker_start_failed",
        False,
        "the worker process did not start (or the old one did not stop)",
    ),
    68: (
        "deps_missing",
        False,
        "numpy could not be installed or imported on the host, so benchmarks cannot run.",
    ),
    69: (
        "venv_unavailable",
        False,
        "the host can't create a Python virtual environment and has no pip or uv. "
        "On Ubuntu / DGX OS run: sudo apt install python3-venv python3-pip",
    ),
    76: (
        "upgrade_rolled_back",
        True,
        "the new worker did not start, so the previous one was restored and is serving",
    ),
    75: (
        "bootstrap_busy",
        True,
        "the host is busy: another bootstrap is running, or jobs are running and the "
        "package change waits until they finish",
    ),
}

SAFE_ARG = re.compile(r"^[A-Za-z0-9_.+/-]+$")


@dataclass(frozen=True)
class SshTarget:
    target: str
    user: str | None = None
    port: int | None = None


@dataclass
class ResolvedTarget:
    hostname: str
    port: int
    user: str | None
    global_known_hosts_files: list[str]
    proxy: bool  # ProxyCommand/ProxyJump: ssh-keyscan can't reach the host directly


# Command-line -o values override ~/.ssh/config, so these always apply.
HARDENING_OPTS = [
    "-o", "BatchMode=yes",
    "-o", "RemoteCommand=none",
    "-o", "RequestTTY=no",
    "-o", "ControlMaster=no",
    "-o", "ControlPath=none",
    "-o", "PermitLocalCommand=no",
    "-o", "ForwardAgent=no",
    "-o", "ForwardX11=no",
    "-o", "UpdateHostKeys=no",
]  # fmt: skip


GPU_MODES = ("auto", "cuda")
# CuPy is ~70 MB; the PyPI CUDA toolkit fallback ~1.3 GB, plus two smoke tests.
GPU_SUPPORT_TIMEOUT = 3600.0


def without_control(opts: list[str]) -> list[str]:
    """Drop ("-o", "Control...") pairs: the tunnel's master sets its own."""
    pairs = zip(opts[::2], opts[1::2], strict=True)
    return [x for flag, value in pairs if not value.startswith("Control") for x in (flag, value)]


# Records each key the host presents; prints nothing, so verification still fails.
# Called as: capture %I %H %t %K. ssh also calls it with I=ORDER and no key (t/K are
# "NONE") before key exchange; only real host-key lookups are recorded.
CAPTURE_SCRIPT = (
    "#!/bin/sh\n"
    'case "$1" in HOSTNAME|ADDRESS) ;; *) exit 0 ;; esac\n'
    'case "$3" in NONE|"") exit 0 ;; esac\n'
    'printf "%s %s %s\\n" "$2" "$3" "$4" >> "$(dirname "$0")/keys"\n'
)
HOST_KEY_TYPES = re.compile(
    r"^(ssh-ed25519|ssh-rsa|ecdsa-sha2-nistp(256|384|521)|"
    r"sk-ssh-ed25519@openssh\.com|sk-ecdsa-sha2-nistp256@openssh\.com)$"
)


def split_paths(value: str) -> list[str]:
    """`ssh -G` prints multi-path values space-separated and unquoted; rejoin tokens
    while the joined path exists, so "/Library/Application Support/kh" survives."""
    tokens = value.split()
    out: list[str] = []
    i = 0
    while i < len(tokens):
        j = len(tokens)
        while j > i + 1 and not Path(os.path.expanduser(" ".join(tokens[i:j]))).exists():
            j -= 1
        out.append(" ".join(tokens[i:j]))
        i = j
    return out


def ssh_list_value(paths: list[str]) -> str:
    """Value for a multi-path ssh option: whitespace-separated, paths quoted."""
    out = []
    for path in paths:
        if '"' in path or "\n" in path:
            raise RunnerError(f"unsupported path for ssh: {path!r}", transient=False, code="config")
        out.append(f'"{path}"' if any(c.isspace() for c in path) else path)
    return " ".join(out)


@dataclass
class HostKey:
    key_type: str
    fingerprint: str
    line: str


def classify_ssh_error(stderr: str) -> tuple[str, bool]:
    """Map ssh stderr to (code, transient)."""
    s = stderr.lower()
    if "remote host identification has changed" in s:
        return "hostkey_changed", False
    if "host key verification failed" in s or "no ed25519 host key is known" in s:
        return "hostkey_unknown", False
    if "permission denied" in s:
        return "auth_failed", False
    if "administratively prohibited" in s:
        return "forwarding_denied", False
    if "could not resolve hostname" in s:
        return "unresolvable", False
    if "connection refused" in s or "timed out" in s or "no route to host" in s:
        return "unreachable", True
    return "ssh_error", True


def fingerprint(key_b64: str) -> str:
    raw = base64.b64decode(key_b64)
    return "SHA256:" + base64.b64encode(hashlib.sha256(raw).digest()).decode().rstrip("=")


def _valid_host_key(key_type: str, key_b64: str) -> bool:
    """A known key type whose blob really starts with that type (rejects 'NONE')."""
    if not HOST_KEY_TYPES.match(key_type):
        return False
    try:
        blob = base64.b64decode(key_b64, validate=True)
    except (ValueError, binascii.Error):
        return False
    if len(blob) < 4:
        return False
    n = int.from_bytes(blob[:4], "big")
    return blob[4 : 4 + n] == key_type.encode()


def parse_keyscan(output: str) -> list[HostKey]:
    """Parse known_hosts-format lines (ssh-keyscan output or captured keys)."""
    keys: list[HostKey] = []
    seen: set[str] = set()
    for line in output.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) < 3:
            continue
        line = " ".join(parts[:3])
        if line in seen or not _valid_host_key(parts[1], parts[2]):
            continue
        keys.append(HostKey(parts[1], fingerprint(parts[2]), line))
        seen.add(line)
    return keys


def worker_source_files(worker_dir: Path) -> list[tuple[str, bytes]]:
    """(archive name, content) of everything uploaded to a host, in a fixed order."""
    files = [
        (f"newton_worker/{path.name}", path.read_bytes())
        for path in sorted((worker_dir / "newton_worker").glob("*.py"))
    ]
    files.append(("bootstrap.sh", (worker_dir / "bootstrap.sh").read_bytes()))
    return files


def worker_source_digest(worker_dir: Path) -> str:
    """Content hash of the worker source; a host reporting another value runs
    stale code and gets re-bootstrapped."""
    return digest_of(worker_source_files(worker_dir))


def digest_of(files: list[tuple[str, bytes]]) -> str:
    h = hashlib.sha256()
    for name, data in files:
        h.update(name.encode() + b"\0" + len(data).to_bytes(8, "big"))
        h.update(data)
    return h.hexdigest()


@dataclass(frozen=True)
class WorkerSource:
    """One snapshot of the worker source: the tarball we upload and its digest."""

    digest: str
    tarball: bytes

    @classmethod
    def load(cls, worker_dir: Path) -> WorkerSource:
        files = worker_source_files(worker_dir)
        return cls(digest_of(files), _tarball(files))


def worker_source_tarball(worker_dir: Path) -> bytes:
    return WorkerSource.load(worker_dir).tarball


def _tarball(files: list[tuple[str, bytes]]) -> bytes:
    """Package the worker source plus its SOURCE_DIGEST for upload."""
    files = [*files, ("SOURCE_DIGEST", (digest_of(files) + "\n").encode())]
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        for name, data in files:
            info = tarfile.TarInfo(name)
            info.size = len(data)
            info.mode = 0o755 if name.endswith(".sh") else 0o644
            tar.addfile(info, io.BytesIO(data))
    return buf.getvalue()


def _tail(text: str, lines: int = 15) -> str:
    return "\n".join(text.strip().splitlines()[-lines:])


class SshClient:
    def __init__(
        self,
        target: SshTarget,
        known_hosts_path: Path,
        ssh: str = "ssh",
        ssh_keyscan: str = "ssh-keyscan",
        log_dir: Path | None = None,
    ) -> None:
        self.target = target
        self.known_hosts_path = known_hosts_path
        self.ssh = ssh
        self.ssh_keyscan = ssh_keyscan
        self.log_dir = log_dir
        self._resolved: ResolvedTarget | None = None
        self._home: str | None = None

    # -- config ---------------------------------------------------------------
    def _target_opts(self) -> list[str]:
        opts = []
        if self.target.user:
            opts += ["-l", self.target.user]
        if self.target.port:
            opts += ["-p", str(self.target.port)]
        return opts

    async def resolve(self) -> ResolvedTarget:
        if self._resolved is not None:
            return self._resolved
        rc, out, err = await self._exec([self.ssh, "-G", *self._target_opts(), self.target.target])
        if rc != 0:
            raise RunnerError(f"ssh -G failed: {err.strip()}", transient=False, code="config")
        cfg: dict[str, str] = {}
        for line in out.splitlines():
            key, _, value = line.partition(" ")
            cfg.setdefault(key.lower(), value.strip())
        defaults = "/etc/ssh/ssh_known_hosts /etc/ssh/ssh_known_hosts2"
        proxy = any(cfg.get(k, "none").lower() != "none" for k in ("proxycommand", "proxyjump"))
        self._resolved = ResolvedTarget(
            hostname=cfg.get("hostname", self.target.target),
            port=int(cfg.get("port", "22")),
            user=cfg.get("user"),
            global_known_hosts_files=split_paths(cfg.get("globalknownhostsfile", defaults)),
            proxy=proxy,
        )
        return self._resolved

    async def connection_opts(self) -> list[str]:
        """Host-key verification, timeouts and target options (no hardening)."""
        resolved = await self.resolve()
        # Our trusted keys join the *global* list, leaving UserKnownHostsFile (and
        # NVIDIA Sync's or any other tool's settings for it) untouched.
        known = ssh_list_value([*resolved.global_known_hosts_files, str(self.known_hosts_path)])
        return [
            "-o", "StrictHostKeyChecking=yes",
            "-o", f"GlobalKnownHostsFile={known}",
            "-o", "ConnectTimeout=15",
            "-o", "ServerAliveInterval=15",
            "-o", "ServerAliveCountMax=3",
            *self._target_opts(),
        ]  # fmt: skip

    async def base_args(self) -> list[str]:
        return [self.ssh, *HARDENING_OPTS, *await self.connection_opts()]

    # -- execution ------------------------------------------------------------
    @staticmethod
    async def _exec(
        argv: list[str], stdin: bytes | None = None, timeout: float = 60
    ) -> tuple[int, str, str]:
        proc = await asyncio.create_subprocess_exec(
            *argv,
            stdin=asyncio.subprocess.PIPE if stdin is not None else asyncio.subprocess.DEVNULL,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        try:
            out, err = await asyncio.wait_for(proc.communicate(stdin), timeout=timeout)
        except TimeoutError as e:
            proc.kill()
            await proc.wait()
            raise RunnerError(f"{argv[0]} timed out after {timeout}s", code="timeout") from e
        return proc.returncode or 0, out.decode(errors="replace"), err.decode(errors="replace")

    async def run_raw(
        self, remote_command: str, stdin: bytes | None = None, timeout: float = 120
    ) -> tuple[int, str, str]:
        """Run a fixed remote command string; SSH-level failures (exit 255) raise,
        the remote command's own exit status is returned."""
        argv = [
            *await self.base_args(),
            "-o", "ClearAllForwardings=yes",  # no LocalForward from the user's config
            self.target.target,
            "--",
            remote_command,
        ]  # fmt: skip
        rc, out, err = await self._exec(argv, stdin, timeout)
        if rc == 255:
            code, transient = classify_ssh_error(err)
            raise RunnerError(f"ssh: {err.strip()[-500:]}", transient=transient, code=code)
        return rc, out, err

    async def run(
        self, remote_command: str, stdin: bytes | None = None, timeout: float = 120
    ) -> str:
        """Run a fixed remote command string. Raises RunnerError on failure."""
        rc, out, err = await self.run_raw(remote_command, stdin, timeout)
        if rc != 0:
            raise RunnerError(
                f"remote command failed ({rc}): {err.strip()[-1000:]}",
                transient=False,
                code="remote_failed",
            )
        return out

    async def check(self) -> dict[str, Any]:
        out = await self.run(REMOTE_PROBE, timeout=30)
        return {"uname": out.strip()}

    async def remote_home(self) -> str:
        if self._home is None:
            out = await self.run(REMOTE_HOME, timeout=30)
            found = re.findall(r"NEWTON-HOME:(.*?):END", out)
            home = found[-1] if found else ""
            if not home.startswith("/") or any(c in home for c in "\n\r:"):
                raise RunnerError(
                    f"unexpected remote home directory: {home!r}", transient=False, code="config"
                )
            self._home = home.rstrip("/")
        return self._home

    async def worker_socket(self) -> str:
        return f"{await self.remote_home()}/{WORKER_SOCKET}"

    # -- host keys ------------------------------------------------------------
    async def scan_host_keys(self) -> list[HostKey]:
        """The keys the host presents, as the exact known_hosts lines ssh will look
        up later (honours HostKeyAlias, non-standard ports and ProxyCommand/ProxyJump
        aliases such as NVIDIA Sync's Tailscale mode). Nothing is trusted here: the
        probe runs with strict checking and empty known_hosts, so it always stops at
        host key verification, before authentication."""
        with tempfile.TemporaryDirectory(prefix="newton-hostkey-") as tmp:
            script = Path(tmp) / "capture"
            script.write_text(CAPTURE_SCRIPT)
            script.chmod(0o700)
            argv = [
                self.ssh,
                *HARDENING_OPTS,
                "-o", "StrictHostKeyChecking=yes",
                "-o", "UserKnownHostsFile=/dev/null",
                "-o", "GlobalKnownHostsFile=/dev/null",
                "-o", "CheckHostIP=no",
                "-o", f'KnownHostsCommand="{script}" %I %H %t %K',
                "-o", "ConnectTimeout=15",
                "-o", "ClearAllForwardings=yes",
                *self._target_opts(),
                self.target.target,
                "--",
                "true",
            ]  # fmt: skip
            _, _, err = await self._exec(argv, timeout=45)
            captured = Path(tmp, "keys").read_text() if Path(tmp, "keys").exists() else ""
        keys = parse_keyscan(captured)
        if keys:
            return keys
        if "bad configuration option" in err.lower() and not (await self.resolve()).proxy:
            return await self._keyscan()  # OpenSSH < 8.5 has no KnownHostsCommand
        code, transient = classify_ssh_error(err)
        if code == "hostkey_unknown":
            code = "hostkey_scan_failed"
        raise RunnerError(
            f"could not read the host's key: {err.strip()[-300:]}", transient=transient, code=code
        )

    async def _keyscan(self) -> list[HostKey]:
        r = await self.resolve()
        rc, out, err = await self._exec(
            [self.ssh_keyscan, "-T", "10", "-p", str(r.port), r.hostname], timeout=30
        )
        keys = parse_keyscan(out)
        if not keys:
            raise RunnerError(f"no host keys found: {err.strip()[-300:]}", code="unreachable")
        return keys

    async def trust_host_keys(self, fingerprints: list[str]) -> list[HostKey]:
        """Re-scan and persist only keys whose fingerprints the user approved."""
        wanted = set(fingerprints)
        keys = [k for k in await self.scan_host_keys() if k.fingerprint in wanted]
        if not keys:
            raise RunnerError(
                "none of the approved fingerprints match the host's current keys",
                transient=False,
                code="hostkey_mismatch",
            )
        self.known_hosts_path.parent.mkdir(parents=True, exist_ok=True)
        existing = (
            set(self.known_hosts_path.read_text().splitlines())
            if self.known_hosts_path.exists()
            else set()
        )
        with open(self.known_hosts_path, "a") as f:
            for k in keys:
                if k.line not in existing:
                    f.write(k.line + "\n")
        self.known_hosts_path.chmod(0o600)
        return keys

    # -- worker lifecycle -------------------------------------------------------
    async def bootstrap(
        self,
        worker_dir: Path,
        token: str,
        python: str = "python3",
        use_venv: bool = True,
        install_deps: bool = True,
        source: WorkerSource | None = None,
    ) -> dict[str, Any]:
        """Upload the worker into a fresh staging dir and run its bootstrap.sh.
        On any failure the host keeps its previous source, venv and worker."""
        if not SAFE_ARG.match(python) or python.startswith("-"):
            raise RunnerError("invalid python path", transient=False, code="config")
        source = source or WorkerSource.load(worker_dir)
        args = ["--python", python]
        if not use_venv:
            args.append("--no-venv")
        if not install_deps:
            args.append("--no-deps")
        stage = new_stage()
        rc, _, err = await self.run_raw(
            f"{REMOTE_UPLOAD_SOURCE} sh {stage}", stdin=source.tarball, timeout=300
        )
        if rc != 0:
            # e.g. a full disk; nothing has changed on the host yet.
            raise RunnerError(f"uploading the worker failed: {_tail(err)}", code="upload_failed")
        token_id = hashlib.sha256(token.encode()).hexdigest()[:16]
        await self.run(f"{REMOTE_WRITE_TOKEN} sh {token_id}", stdin=token.encode())
        rc, out, err = await self.run_raw(remote_bootstrap_command(stage, args), timeout=900)
        if rc != 0:
            code, transient, hint = BOOTSTRAP_ERRORS.get(
                rc, ("bootstrap_crashed", False, f"bootstrap.sh failed with exit code {rc}")
            )
            raise RunnerError(f"{hint}\n{_tail(err)}", transient=transient, code=code)
        lines = [ln for ln in out.strip().splitlines() if ln.strip()]
        try:
            status: dict[str, Any] = json.loads(lines[-1])
        except (IndexError, json.JSONDecodeError) as e:
            raise RunnerError(f"unexpected bootstrap output: {out[-500:]}", code="bootstrap") from e
        if not status.get("running"):
            raise RunnerError(f"worker not running after bootstrap: {status}", code="bootstrap")
        if not (status.get("deps") or {}).get("numpy"):
            # Defence in depth: bootstrap.sh gates on numpy, but never trust one layer.
            raise RunnerError(
                f"worker started without numpy: {status.get('deps')}",
                transient=False,
                code="deps_missing",
            )
        return status

    async def gpu_support(
        self,
        mode: str,
        python: str = "python3",
        use_venv: bool = True,
        install_deps: bool = True,
        timeout: float = GPU_SUPPORT_TIMEOUT,
    ) -> dict[str, Any] | None:
        """Install/verify GPU support with the installed worker (it must already
        run): returns the host's gpu.json, or None if it has no NVIDIA driver.
        `mode`: auto (throttled retries) | cuda (the user asked: try now)."""
        if mode not in GPU_MODES:
            raise RunnerError(f"invalid gpu mode {mode!r}", transient=False, code="config")
        if not SAFE_ARG.match(python) or python.startswith("-"):
            raise RunnerError("invalid python path", transient=False, code="config")
        args = ["--gpu-only", mode, "--python", python]
        if not use_venv:
            args.append("--no-venv")
        if not install_deps:
            args.append("--no-deps")
        command = " ".join(['sh "$HOME/.newton/src/bootstrap.sh"', *(shlex.quote(a) for a in args)])
        rc, out, err = await self.run_raw(command, timeout=timeout)
        if rc != 0:
            code, transient, hint = BOOTSTRAP_ERRORS.get(
                rc, ("gpu_support_crashed", False, f"GPU support failed with exit code {rc}")
            )
            if code == "bootstrap_busy":
                hint = "jobs are running on the host; install GPU support once they finish"
            raise RunnerError(f"{hint}\n{_tail(err)}", transient=transient, code=code)
        lines = [ln for ln in out.strip().splitlines() if ln.strip()]
        try:
            state = json.loads(lines[-1])
        except (IndexError, json.JSONDecodeError) as e:
            raise RunnerError(
                f"unexpected GPU support output: {out[-500:]}", code="bootstrap"
            ) from e
        return state if isinstance(state, dict) else None

    async def open_tunnel(self, remote_socket: str, timeout: float = 20) -> Tunnel:
        """Forward a private local Unix socket to the worker's Unix socket on the host.

        A dedicated ControlMaster connection is opened with ClearAllForwardings, so
        LocalForward/RemoteForward/DynamicForward lines in the user's ssh config are
        never inherited (they would collide with the user's own sessions); the worker
        forward is then added through the master. Both sockets live in a fresh 0700
        directory: no other local user can reach the worker or squat its endpoint.
        """
        if not remote_socket.startswith("/") or ":" in remote_socket:
            raise RunnerError(
                f"bad remote socket {remote_socket!r}", transient=False, code="config"
            )
        tunnel = await self._master(timeout)
        try:
            await tunnel.forward(remote_socket)
        except BaseException:
            await asyncio.shield(tunnel.close())
            raise
        return tunnel

    async def open_port_forward(self, remote_port: int, local_port: int, timeout: float = 20
                                ) -> Tunnel:  # fmt: skip
        """Forward 127.0.0.1:local_port on this Mac to 127.0.0.1:remote_port on the
        host (a model service), over its own hardened master connection."""
        for port in (remote_port, local_port):
            if not isinstance(port, int) or not 1024 <= port <= 65535:
                raise RunnerError(f"bad port {port!r}", transient=False, code="config")
        tunnel = await self._master(timeout)
        try:
            await tunnel.forward_tcp(local_port, remote_port)
        except BaseException:
            await asyncio.shield(tunnel.close())
            raise
        return tunnel

    async def _master(self, timeout: float) -> Tunnel:
        """A private ControlMaster that inherits none of the user's own forwards."""
        tunnel = Tunnel(self.ssh, self.target.target, self.log_dir)
        master = [
            self.ssh,
            *without_control(HARDENING_OPTS),
            "-o", f"ControlPath={tunnel.control_path}",
            "-o", "ControlMaster=yes",
            "-o", "ControlPersist=no",
            "-o", "ClearAllForwardings=yes",
            "-o", "Tunnel=no",
            "-o", "StreamLocalBindMask=0177",
            "-o", "StreamLocalBindUnlink=yes",
            *await self.connection_opts(),
            "-N",
            self.target.target,
        ]  # fmt: skip
        try:
            await tunnel.start(master, timeout)
        except BaseException:
            await asyncio.shield(tunnel.close())
            raise
        return tunnel


class Tunnel:
    """A ControlMaster ssh connection plus one stream-local forward."""

    def __init__(self, ssh: str, target: str, log_dir: Path | None) -> None:
        self.ssh = ssh
        self.target = target
        # Short (sun_path limit) and private (mkdtemp is 0700, per-user TMPDIR on macOS).
        self.dir = Path(tempfile.mkdtemp(prefix="newton-"))
        self.control_path = str(self.dir / "cm")
        self.socket_path = str(self.dir / "w.sock")
        self.log_path = (log_dir or self.dir) / f"tunnel-{self.dir.name}.log"
        self.proc: asyncio.subprocess.Process | None = None
        self.local_port: int | None = None

    @property
    def alive(self) -> bool:
        return self.proc is not None and self.proc.returncode is None

    def log_text(self) -> str:
        if not self.log_path.exists():
            return ""
        return self.log_path.read_text(errors="replace")[-4000:]

    def _mux(self, *args: str) -> list[str]:
        # -F /dev/null: the mux client must not re-send the config's forwards.
        return [self.ssh, "-F", "/dev/null", "-S", self.control_path, *args, self.target]

    async def start(self, argv: list[str], timeout: float) -> None:
        self.log_path.parent.mkdir(parents=True, exist_ok=True)
        with open(self.log_path, "wb") as log:
            self.proc = await asyncio.create_subprocess_exec(
                *argv,
                stdin=asyncio.subprocess.DEVNULL,
                stdout=asyncio.subprocess.DEVNULL,
                stderr=log,
            )
        loop = asyncio.get_running_loop()
        deadline = loop.time() + timeout
        while loop.time() < deadline and self.proc.returncode is None:
            rc, _, _ = await SshClient._exec(self._mux("-O", "check"), timeout=10)
            if rc == 0:
                return
            await asyncio.sleep(0.1)
        err = self.log_text()
        code, transient = classify_ssh_error(err)
        if self.proc.returncode is None:  # still connecting after the timeout
            code, transient = "timeout", True
        raise RunnerError(f"tunnel failed: {err.strip()[-500:]}", transient=transient, code=code)

    async def forward(self, remote_socket: str) -> None:
        rc, _, err = await SshClient._exec(
            self._mux("-O", "forward", "-L", f"{self.socket_path}:{remote_socket}"), timeout=15
        )
        if rc != 0:
            code, transient = classify_ssh_error(err + self.log_text())
            raise RunnerError(
                f"could not forward to the worker: {err.strip()[-300:]}",
                transient=transient,
                code=code,
            )

    async def forward_tcp(self, local_port: int, remote_port: int) -> None:
        """127.0.0.1:local_port here -> 127.0.0.1:remote_port on the host (loopback on
        both ends: nothing is exposed to the network)."""
        spec = f"127.0.0.1:{local_port}:127.0.0.1:{remote_port}"
        rc, _, err = await SshClient._exec(self._mux("-O", "forward", "-L", spec), timeout=15)
        if rc != 0:
            code, transient = classify_ssh_error(err + self.log_text())
            raise RunnerError(
                f"could not forward port {remote_port}: {err.strip()[-300:]}",
                transient=transient,
                code=code,
            )
        self.local_port = local_port

    async def close(self) -> None:
        if self.proc is not None and self.proc.returncode is None:
            try:
                await SshClient._exec(self._mux("-O", "exit"), timeout=5)
            except RunnerError:
                pass
            if self.proc.returncode is None:
                self.proc.terminate()
            try:
                await asyncio.wait_for(self.proc.wait(), timeout=5)
            except TimeoutError:
                self.proc.kill()
                await self.proc.wait()
        shutil.rmtree(self.dir, ignore_errors=True)
        self.log_path.unlink(missing_ok=True)


UPGRADE_BACKOFF_START = 600.0
UPGRADE_BACKOFF_MAX = 6 * 3600.0
RESTART_BACKOFF_START = 30.0
RESTART_BACKOFF_MAX = 600.0

RunnerEventHook = Callable[[str, dict[str, Any]], None]


class SshRunner(WorkerClientRunner):
    """Worker over an SSH tunnel, self-maintaining:

    - worker down (reboot, OTA update): bootstrap restarts it once per connect;
    - stale worker code (digest differs): bootstrap upgrades it. If that fails
      the host keeps its old worker (bootstrap.sh changes nothing on failure), we
      keep serving through it and retry with exponential backoff. New jobs are
      only refused when the old worker speaks another protocol version.
    """

    def __init__(
        self,
        host_id: str,
        ssh: SshClient,
        token: str,
        worker_dir: Path,
        python: str = "python3",
        use_venv: bool = True,
        install_deps: bool = True,
        on_event: RunnerEventHook | None = None,
    ) -> None:
        self.host_id = host_id
        self.ssh = ssh
        self.token = token
        self.python = python
        self.use_venv = use_venv
        self.install_deps = install_deps
        self.on_event = on_event
        # One snapshot per runner: what we upload is exactly what we compare against.
        self.source = WorkerSource.load(worker_dir)
        self.worker_dir = worker_dir
        self.tunnel: Tunnel | None = None
        self.upgrade_pending: str | None = None
        self.protocol_mismatch = False
        self._upgrade_failures = 0
        self._upgrade_retry_at = 0.0
        self._restart_failures = 0
        self._restart_retry_at = 0.0
        self._restart_error: RunnerError | None = None
        self._closed = False
        self._lock = asyncio.Lock()

    @property
    def source_digest(self) -> str:
        return self.source.digest

    def _emit(self, kind: str, data: dict[str, Any]) -> None:
        if self.on_event is not None:
            self.on_event(kind, data)

    def _check_open(self) -> None:
        if self._closed:
            raise RunnerError("runner closed", code="closed")

    async def ensure_ready(self) -> None:
        async with self._lock:
            self._check_open()
            connected = self.tunnel is not None and self.tunnel.alive and self.client is not None
            upgrade_due = (
                self.upgrade_pending is not None and time.monotonic() >= self._upgrade_retry_at
            )
            if connected and not upgrade_due:
                return
            try:
                await self._connect(restart_worker=True)
            finally:
                if self._closed:
                    await self._release()

    async def _bootstrap(self) -> dict[str, Any]:
        self._check_open()
        # Deps follow the host setting; pip/uv are skipped when the pins are met.
        status = await self.ssh.bootstrap(
            self.worker_dir,
            self.token,
            self.python,
            self.use_venv,
            self.install_deps,
            source=self.source,
        )
        self._check_open()
        return status

    async def _raise_if_forwarding_refused(self, cause: RunnerError) -> None:
        rc, _, _ = await self.ssh.run_raw(REMOTE_WORKER_ALIVE, timeout=30)
        if rc == 0:
            raise RunnerError(
                "the worker runs on the host, but its sshd refuses to forward to it; allow "
                "'AllowStreamLocalForwarding yes' (and no DisableForwarding / no-port-forwarding "
                "restriction for this key) on the host",
                transient=False,
                code="forwarding_denied",
            ) from cause

    def _restart_failed(self, error: RunnerError) -> None:
        self._restart_failures += 1
        delay = min(RESTART_BACKOFF_START * 2 ** (self._restart_failures - 1), RESTART_BACKOFF_MAX)
        self._restart_retry_at = time.monotonic() + delay
        self._restart_error = error
        self._emit("worker_restart_failed", {"code": error.code, "retry_in_seconds": delay})

    async def _restart(self) -> None:
        """Start the installed worker after it died (reboot, OTA update, crash),
        with backoff: a host whose worker can't start is not re-bootstrapped on
        every call."""
        cached = self._restart_error
        if cached is not None and time.monotonic() < self._restart_retry_at:
            raise RunnerError(str(cached), transient=cached.transient, code=cached.code)
        try:
            await self._bootstrap()
        except RunnerError as e:
            if e.code == "closed":
                raise
            self._restart_failed(e)
            raise
        self._emit("worker_restarted", {"digest": self.source_digest})

    async def _open(self) -> dict[str, Any]:
        await self._release()
        self.tunnel = await self.ssh.open_tunnel(await self.ssh.worker_socket())
        self._check_open()
        self.client = WorkerClient("http://worker", self.token, uds=self.tunnel.socket_path)
        return await self.client.health()

    async def _connect(self, restart_worker: bool, allow_upgrade: bool = True) -> dict[str, Any]:
        """Open the tunnel and return the worker's /health, restarting or upgrading
        the worker when needed."""
        try:
            health = await self._open()
        except RunnerError as e:
            await self._release()
            if e.code != "unreachable":
                raise
            # OpenSSH reports a refused forward exactly like a dead worker ("connect
            # failed"), so ask the host itself whether the worker is running.
            await self._raise_if_forwarding_refused(e)
            if not restart_worker:
                raise
            self._check_open()
            await self._restart()
            try:
                return await self._connect(restart_worker=False, allow_upgrade=False)
            except RunnerError as again:
                self._restart_failed(again)  # restarted, still unreachable: back off
                raise
        self._check_open()
        remote = health.get("source_digest")
        remote = remote if isinstance(remote, str) and DIGEST_RE.match(remote) else None
        self.protocol_mismatch = health.get("protocol") != WORKER_PROTOCOL
        self._restart_failures, self._restart_error = 0, None
        if remote == self.source_digest:
            self._upgrade_failures, self._upgrade_retry_at = 0, 0.0
            self.upgrade_pending = None
            return health
        if not allow_upgrade or time.monotonic() < self._upgrade_retry_at:
            return health  # keep using the running worker until the backoff expires
        await self._release()
        try:
            await self._bootstrap()
        except RunnerError as e:
            if e.code == "closed":
                raise
            self._upgrade_failed(remote, e)
            try:
                return await self._connect(restart_worker=False, allow_upgrade=False)
            except RunnerError:
                raise e from None
        upgraded = await self._connect(restart_worker=False, allow_upgrade=False)
        if upgraded.get("source_digest") == self.source_digest:
            self._emit("worker_upgraded", {"from": remote, "to": self.source_digest})
        else:
            # A host that misreports its digest, or an upload that didn't land:
            # don't claim success, and back off instead of re-bootstrapping forever.
            self._upgrade_failed(
                remote,
                RunnerError(
                    f"after the upgrade the worker reports {upgraded.get('source_digest')!r}",
                    code="upgrade_unverified",
                ),
            )
        return upgraded

    def retry_now(self) -> None:
        """The user asked to check the host (maybe after fixing it): retry a failed
        restart now. A failed *upgrade* keeps its backoff: the old worker is serving,
        and each attempt can mean a long package install."""
        self._restart_retry_at = 0.0

    def _upgrade_failed(self, remote: str | None, error: RunnerError) -> None:
        self._upgrade_failures += 1
        delay = min(UPGRADE_BACKOFF_START * 2 ** (self._upgrade_failures - 1), UPGRADE_BACKOFF_MAX)
        self._upgrade_retry_at = time.monotonic() + delay
        self.upgrade_pending = error.code
        self._emit(
            "worker_upgrade_failed",
            {
                "from": remote,
                "to": self.source_digest,
                "code": error.code,
                "error": str(error)[-2000:],
                "retry_in_seconds": delay,
            },
        )

    async def submit(self, manifest: dict[str, Any], bundle: bytes) -> dict[str, Any]:
        await self.ensure_ready()
        if self.protocol_mismatch:
            raise RunnerError(
                "the host runs a worker with another protocol version; "
                "new jobs wait until its upgrade succeeds",
                code="worker_upgrade_pending",
            )
        return await super().submit(manifest, bundle)

    async def _release(self) -> None:
        await super().close()
        if self.tunnel is not None:
            await self.tunnel.close()
            self.tunnel = None

    async def reset(self) -> None:
        async with self._lock:
            await self._release()

    async def close(self) -> None:
        """Permanent: an in-flight connect notices and releases what it opened."""
        self._closed = True
        await self._release()
